name: media_break_points
description: This package allows you to apply values depending on media breakpoint provided.
version: 1.5.1
homepage: https://github.com/glenfordwilliams/flutter_media_break_points

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
