name: media_break_points
description: Adaptive layout primitives and container-aware responsive builders for Flutter.
version: 2.0.0-wip
homepage: https://github.com/glenfordwilliams/flutter_media_break_points
repository: https://github.com/glenfordwilliams/flutter_media_break_points
issue_tracker: https://github.com/glenfordwilliams/flutter_media_break_points/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
